require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SizesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Size. As you add validations to Size, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SizesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sizes as @sizes" do
      size = Size.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:sizes)).to eq([size])
    end
  end

  describe "GET #show" do
    it "assigns the requested size as @size" do
      size = Size.create! valid_attributes
      get :show, params: {id: size.to_param}, session: valid_session
      expect(assigns(:size)).to eq(size)
    end
  end

  describe "GET #new" do
    it "assigns a new size as @size" do
      get :new, params: {}, session: valid_session
      expect(assigns(:size)).to be_a_new(Size)
    end
  end

  describe "GET #edit" do
    it "assigns the requested size as @size" do
      size = Size.create! valid_attributes
      get :edit, params: {id: size.to_param}, session: valid_session
      expect(assigns(:size)).to eq(size)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Size" do
        expect {
          post :create, params: {size: valid_attributes}, session: valid_session
        }.to change(Size, :count).by(1)
      end

      it "assigns a newly created size as @size" do
        post :create, params: {size: valid_attributes}, session: valid_session
        expect(assigns(:size)).to be_a(Size)
        expect(assigns(:size)).to be_persisted
      end

      it "redirects to the created size" do
        post :create, params: {size: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Size.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved size as @size" do
        post :create, params: {size: invalid_attributes}, session: valid_session
        expect(assigns(:size)).to be_a_new(Size)
      end

      it "re-renders the 'new' template" do
        post :create, params: {size: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested size" do
        size = Size.create! valid_attributes
        put :update, params: {id: size.to_param, size: new_attributes}, session: valid_session
        size.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested size as @size" do
        size = Size.create! valid_attributes
        put :update, params: {id: size.to_param, size: valid_attributes}, session: valid_session
        expect(assigns(:size)).to eq(size)
      end

      it "redirects to the size" do
        size = Size.create! valid_attributes
        put :update, params: {id: size.to_param, size: valid_attributes}, session: valid_session
        expect(response).to redirect_to(size)
      end
    end

    context "with invalid params" do
      it "assigns the size as @size" do
        size = Size.create! valid_attributes
        put :update, params: {id: size.to_param, size: invalid_attributes}, session: valid_session
        expect(assigns(:size)).to eq(size)
      end

      it "re-renders the 'edit' template" do
        size = Size.create! valid_attributes
        put :update, params: {id: size.to_param, size: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested size" do
      size = Size.create! valid_attributes
      expect {
        delete :destroy, params: {id: size.to_param}, session: valid_session
      }.to change(Size, :count).by(-1)
    end

    it "redirects to the sizes list" do
      size = Size.create! valid_attributes
      delete :destroy, params: {id: size.to_param}, session: valid_session
      expect(response).to redirect_to(sizes_url)
    end
  end

end
